# Machine Learning Lab Evaluation

This lab includes two tasks: regression and classification. Each task compares three models: two traditional machine learning models and one neural network, with evaluations based on three metrics.

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from tensorflow.keras.utils import to_categorical


## Task 1: Regression

### Step 1: Load Dataset
We use the Boston Housing dataset for the regression task.

Use Numpy library to import dataset.
<br>`numpy.load(FILE_PATH, allow_pickle=True).item()`
<br>The dataset structure is dictionary-format.

In [2]:
# Load the data

# -------------------------------
# Your code here
df = np.load("boston-dataset.npy", allow_pickle=True).item()

# -------------------------------

In [3]:
# Show 3 samples of dataset

# -------------------------------
# Your code here
X = df.data    # ข้อมูล Feature ทั้งหมด
y = df.target  # ข้อมูล Target

print(X[:3])
# -------------------------------

[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]]


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [4]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42

# -------------------------------
# Your code here
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.2 ,random_state=42)
# -------------------------------

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data

# -------------------------------
# Your code here
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# -------------------------------

In [5]:
# Show variable shape

# -------------------------------
# Your code here
print(f"x_train >> {X_train.shape}")
print(f"x_test >> {X_test.shape}")
print(f"y_train >> {y_train.shape}")
print(f"y_test >> {y_test.shape}")

# -------------------------------

x_train >> (101, 13)
x_test >> (405, 13)
y_train >> (101,)
y_test >> (405,)


### Step 3: Train Models
We train three models: Linear Regression, Random Forest Regressor, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [6]:
# Linear Regression
# Create a Linear Regression model
# -------------------------------
# Your code here
lin_model = LinearRegression()
# -------------------------------


# Fit the model
# -------------------------------
# Your code here
lin_model.fit(X_train, y_train)
# -------------------------------


# Predict the target values
# -------------------------------
# Your code here
y_pred = lin_model.predict(X_test)
# -------------------------------

In [7]:
# Random Forest Regressor
# Use RandomForestRegressor to train the model with random_state=42
# -------------------------------
# Your code here
Forest = RandomForestRegressor(random_state=42)
# -------------------------------

# Fit the model
# -------------------------------
# Your code here
Forest.fit(X_train, y_train)
# -------------------------------

# Predict the target values
# -------------------------------
# Your code here
y_pred_tree = Forest.predict(X_test)
# -------------------------------

In [8]:
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function
from tensorflow.keras.optimizers import Adam

nn_model_reg = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

# Compile the model with adam optimizer and mean squared error loss function
# -------------------------------
# Your code here
optimizer = Adam(learning_rate=0.001)
nn_model_reg.compile(optimizer=optimizer,
                     loss = 'mean_absolute_error',
                     )
# -------------------------------

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
nn_model_reg.fit(X_train, y_train,
                 validation_data=(X_test, y_test),
                 epochs=50,
                 batch_size=16)
# -------------------------------

# Predict the target values using the model
# -------------------------------
# Your code here
pred_nn = nn_model_reg.predict(X_test)
# -------------------------------

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 22.7469 - val_loss: 22.3610
Epoch 2/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 22.3547 - val_loss: 21.9590
Epoch 3/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 21.9750 - val_loss: 21.5361
Epoch 4/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 21.5615 - val_loss: 21.0651
Epoch 5/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 21.1045 - val_loss: 20.5263
Epoch 6/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 20.5756 - val_loss: 19.8990
Epoch 7/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 19.9486 - val_loss: 19.1637
Epoch 8/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 19.1934 - val_loss: 18.2961
Epoch 9/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 18.3185 - val_loss: 17.3433
Epoch 10/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 17.3731 - val_loss: 16.2958
Epoch 11/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 16.2299 - val_loss: 15.1235
Epoch 12/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 14.97

### Step 4: Evaluate Models
We evaluate the models using Mean Squared Error (MSE), Mean Absolute Error (MAE), and R² Score.

In [9]:
# Evaluate the models

# -------------------------------
# Your code here
print("Regression Task:")
print("Linear Regression:")
mse = mean_squared_error(y_test, y_pred)
print(f"MSE", mse)
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE", mae)
r2 = r2_score(y_test, y_pred)
print(f"R2 Score", r2)


print("")
print("Random Forest Regression:")
mse_forest = mean_squared_error(y_test, y_pred_tree)
print("MSE:", mse_forest)
mae_forest = mean_absolute_error(y_test, y_pred_tree)
print("MAE:", mae_forest)
r2_forest = r2_score(y_test, y_pred_tree)
print("R2: Score", r2_forest)

print("")
print("Neural Network:")
mse_nn = mean_squared_error(y_test, pred_nn)
print("MSE:", mse_nn)
mae_nn = mean_squared_error(y_test, pred_nn)
print("MAE:", mae_nn)
r2_nn = r2_score(y_test, pred_nn)
print("R2 Score:", r2_nn)
# -------------------------------

Regression Task:
Linear Regression:
MSE 25.564048911173426
MAE 3.5419150344712715
R2 Score 0.707960814349847

Random Forest Regression:
MSE: 21.21378428148151
MAE: 3.0656444444444473
R2: Score 0.7576574701586462

Neural Network:
MSE: 23.622111358481124
MAE: 23.622111358481124
R2 Score: 0.7301451664234277


---
---
---

## Task 2: Classification

### Step 1: Load Dataset
We use the Iris dataset for the classification task.

In [10]:
# Load the data
# -------------------------------
# Your code here
# -------------------------------
CSV_PATH = "iris_dataset.csv"
df = pd.read_csv(CSV_PATH)

# Show the first 5 rows of the dataset
# -------------------------------
# Your code here
# -------------------------------
df.head()

,sepal_length,sepal_width,petal_length,petal_width,target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [11]:
# Split the data into features and target
# -------------------------------
# Your code here
# -------------------------------
X = df.drop('target',axis=1)
y = df['target']


In [12]:
# Show 3 samples of features
# -------------------------------
# Your code here
# -------------------------------
print(X.head(3))

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [13]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42
# -------------------------------
# Your code here
# -------------------------------
X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data
# -------------------------------
# Your code here
# -------------------------------
sc = StandardScaler()
sc.fit_transform(X_train)
sc.transform(X_test)

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751],
       [ 0.84210448,  0.30929911,  0.78699794,  1.09012776],
       [-1.23014297, -0.13788033, -1.33331205, -1.44608785],
       [-0.37686461,  0.98006827, -1.39061772, -1.31260282],
       [-1.10824606,  0.08570939, -1.27600637, -1.44608785],
       [-0.86445224,  1.65083742, -1.27600637, -1.17911778],
       [ 0.59831066,  0.53288883,  0.55777524,  0.55618763],
       [ 0.84210448, -0.

### Step 2.5: Encode Target Variable
We encode the target variable using One-Hot Encoding.

In [14]:
from matplotlib.pyplot import axis
# One-hot encode for neural network
# -------------------------------
# Your code here
# -------------------------------

y_train_one = to_categorical(y_train, num_classes=8)
y_test_one = to_categorical(y_test, num_classes=8)

In [15]:
# Show variable shape
# -------------------------------
# Your code here
# -------------------------------
print("X_train >> ",X_train.shape)
print("X_test >>",X_test.shape)
print("y_trian >> ",y_train.shape)
print("y_test >> ",y_test.shape)

X_train >>  (120, 4)
X_test >> (30, 4)
y_trian >>  (120,)
y_test >>  (30,)


### Step 3: Train Models
We train three models: Logistic Regression, Random Forest Classifier, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [16]:
# Logistic Regression
# Create a Logistic Regression model
# -------------------------------
# Your code here
# -------------------------------
Logis = LogisticRegression()

# Fit the model
# -------------------------------
# Your code here
# -------------------------------

Logis.fit(X_train, y_train)

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------
Logis_pred = Logis.predict(X_test)

In [17]:
# Random Forest Classifier
# Use RandomForestClassifier to train the model with random_state=42
# -------------------------------
# Your code here
# -------------------------------
random = RandomForestClassifier(random_state=42)

# Fit the model
# -------------------------------
# Your code here
# -------------------------------
random.fit(X_train,y_train)

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------
random_pred = random.predict(X_test)

In [18]:
from numpy.testing import verbose
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function
nn_model_cls = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(8, activation='relu')
])

# Compile the model with adam optimizer and categorical crossentropy loss function
# Use accuracy as the metric
# -------------------------------
# Your code here
# -------------------------------
nn_model_cls.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
# -------------------------------
nn_model_cls.fit(X_train, y_train_one,
                epochs=50, batch_size=16,
                validation_data=(X_test, y_test_one)
        )

# Predict the target values using the model
# Use argmax to get the predicted class
# -------------------------------
# Your code here
# -------------------------------
nn_pred = nn_model_cls.predict(X_test)


Epoch 1/50


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.3333 - loss: 10.7162 - val_accuracy: 0.3333 - val_loss: 5.9600
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3333 - loss: 6.0711 - val_accuracy: 0.3333 - val_loss: 5.2607
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3333 - loss: 5.8576 - val_accuracy: 0.3333 - val_loss: 5.1987
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3333 - loss: 5.8117 - val_accuracy: 0.3333 - val_loss: 5.1558
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3750 - loss: 5.7673 - val_accuracy: 0.5667 - val_loss: 5.0986
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6417 - loss: 5.7199 - val_accuracy: 0.7000 - val_loss: 5.0524
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6583 - loss: 5.6872 - val_accuracy: 0.7000 - val_loss: 5.0198
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6583 - loss: 5.6583 - val_accuracy: 0.7000 - val_loss: 4.9928
Epoch 9/50

### Step 4: Evaluate Models
We evaluate the models using Accuracy, Precision, and Recall.

In [19]:
# Evaluate the models
# -------------------------------
# Your code here
# -------------------------------


print('Classification Task:')
print('Logistic Regression:')

print(f" Accuraacy: {accuracy_score(y_test, Logis_pred):.4f}")
print(f" Precision: {precision_score(y_test, Logis_pred, average='weighted'):.4f}")
print(f" Recal: {recall_score(y_test, Logis_pred, average='weighted'):.4f}")
print(f" F1 Scaore: {f1_score(y_test, Logis_pred, average='weighted'):.4f}")

print(f" \nConfusion Matrix:\n {confusion_matrix(y_test, Logis_pred)}")

print('\nRandom Forest Classifier:')

print(f" Accuraacy: {accuracy_score(y_test, random_pred):.4f}")
print(f" Precision: {precision_score(y_test, random_pred, average='weighted'):.4f}")
print(f" Recal: {recall_score(y_test, random_pred, average='weighted'):.4f}")
print(f" F1 Scaore: {f1_score(y_test, random_pred, average='weighted'):.4f}")

print(f" \nConfusion Matrix:\n {confusion_matrix(y_test, random_pred)}")


nn_pred_labels = np.argmax(nn_pred, axis=1)

print("\nNeural Network:")
print(f" Accuracy: {accuracy_score(y_test, nn_pred_labels)}")

print(f" \nConfusion Matrix:\n {confusion_matrix(y_test, nn_pred_labels)}")

Classification Task:
Logistic Regression:
 Accuraacy: 1.0000
 Precision: 1.0000
 Recal: 1.0000
 F1 Scaore: 1.0000
 
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Random Forest Classifier:
 Accuraacy: 1.0000
 Precision: 1.0000
 Recal: 1.0000
 F1 Scaore: 1.0000
 
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Neural Network:
 Accuracy: 0.7
 
Confusion Matrix:
 [[10  0  0]
 [ 0  0  9]
 [ 0  0 11]]
